-- PostgreSQL database creation script
-- Used by services to initialize their respective databases

DROP ROLE IF EXISTS :"APP_USER";
DROP ROLE IF EXISTS :"RO_USER";
DROP DATABASE IF EXISTS :"DB_NAME";

CREATE ROLE :"APP_USER" WITH LOGIN PASSWORD :'APP_PASSWORD';
CREATE ROLE :"RO_USER" WITH LOGIN PASSWORD :'RO_PASSWORD';

CREATE DATABASE :"DB_NAME"
  OWNER :"APP_USER"
  TEMPLATE template0
  ENCODING 'UTF8';

GRANT ALL PRIVILEGES ON DATABASE :"DB_NAME" TO :"APP_USER";
GRANT CONNECT ON DATABASE :"DB_NAME" TO :"RO_USER";
